### ISSUE TITLE
customUrlTosteamID64 - Incorrect SteamID Returned

### ISSUE THREAD

**Issue by browne878** [HerrEurobeat/node-steamid-resolver#1]
Found a bug when testing this package.

When looking up a steam ID from a vanity url it is returning the incorrect ID.

I checked this using the following website:
https://steamid.io/

**Comment by browne878** [comment]
This can be deleted, misread the code xD sorry mate, loving this!

**Comment by 3urobeat** [comment]
Alright, no worries! Glad to hear that you like the library :)
