### ISSUE TITLE
Trying so many way, however everytime error 

### ISSUE THREAD

**Issue by maskalix** [HerrEurobeat/node-steamid-resolver#2]
Hi, i tried to input customURL and always it gives me **ERROR :)**

How to solve that?

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  
  
Can you please provide more information so that I can try and figure out what is going on?  
What is the exact URL your are providing?  
Which function of the lib are you using?  
  
I'm using the lib myself daily and haven't noticed any issues at the moment

**Comment by maskalix** [comment]
Well, i'm not pretty sure, if I'm using it correctly...
Is this right usage?
`const id = steamidResolver.customUrlTosteamID64(url)`

**Comment by 3urobeat** [comment]
Ah no, there is your issue  
The function expects a callback function as the second parameter, it can't just return the value as the function takes a variable amount of time to complete.  
  
Call it like this (take a look at the README of this repo, it explains the parameters):  
```
steamidResolver.customUrlTosteamID64(url, (err, id) => {
    if (err) {
        //handle error if for example the profile couldn't be found, for example:
        console.log(err)
    } else {
        //do whatever you want with the id on success, for example:
        console.log(id)
    }
})
```
So your `(err, id)` is the callback function.
  
I hope that clears it up ^^

**Comment by maskalix** [comment]
Hi, so i tried as you mentioned and well, it works, however give err ([ 'The specified profile could not be found.' ])
What is wrong with my Steam profile, or where is problem? 
This is my steamaccount:
https://steamcommunity.com/id/saintawe/
So i did
const url = https://steamcommunity.com/id/saintawe/;
and it gives that error.
:(

**Comment by maskalix** [comment]
*i did 
const url = "https://steamcommunity.com/id/saintawe/";

forgot to write here quotation marks

**Comment by 3urobeat** [comment]
Works for me:
```
const steamidResolver = require("steamid-resolver")

const url = "https://steamcommunity.com/id/saintawe/"

steamidResolver.customUrlTosteamID64(url, (err, id) => {
    if (err) console.log(err)
        else console.log(id)
})
```
Response: `76561198982739328`

**Comment by 3urobeat** [comment]
I hope this answered your question and I'm going to close this issue.  
If not, don't hesitate to reopen it.  
If you've got another question feel free to open another issue!
