### ISSUE TITLE
Steam Name in SteamID

### ISSUE THREAD

**Issue by Pdzly** [HerrEurobeat/node-steamid-resolver#3]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/34943569/172188872-b85e6c43-48e9-4546-8adc-cb895f31d48e.png">
Why is the Steam Name in the SteamID Value?

**Comment by 3urobeat** [comment]
If I'm looking at the full info object then because Steam provides it like that.  
My name is my steamID as well: https://steamcommunity.com/id/3urobeat?xml=1  
  
The library is just returning the information it gets from Steam

**Comment by 3urobeat** [comment]
I hope this answered your question and I'm going to close this issue.  
If not, don't hesitate to reopen it.  
If you've got another question feel free to open another issue!
